
CREATE DATABASE BDTIENDA2
USE BDTIENDA2

CREATE TABLE CLIENTES2
(
CODCLI INT NOT NULL IDENTITY PRIMARY KEY,
NOMBRE VARCHAR(30) NOT NULL,
GENERO VARCHAR(10) NOT NULL,
LATITUD FLOAT NOT NULL,
LONGITUD FLOAT NOT NULL
)
INSERT INTO CLIENTES2 VALUES ('JUAN', 'MASCULINO',-63, -17)
INSERT INTO CLIENTES2 VALUES ('PEDRO', 'MASCULINO',-62, -18)
INSERT INTO CLIENTES2 VALUES ('MARIA', 'FEMENINO',-64, -17)

SELECT * FROM CLIENTES2

CREATE OR ALTER PROCEDURE SPMOSTRARCLIENTES
AS
BEGIN
 SELECT * FROM CLIENTES2
END

EXEC SPMOSTRARCLIENTES


CREATE OR ALTER PROCEDURE SPBUSCARCLIENTES
@Nom VARCHAR(30)
AS
BEGIN
 SELECT * FROM CLIENTES2 WHERE NOMBRE LIKE '%'+@Nom+'%'
END

EXEC SPMOSTRARCLIENTES 
EXEC SPBUSCARCLIENTES 'U'
EXEC SPBUSCARCLIENTES 'UA'
EXEC SPBUSCARCLIENTES 'UAD'

EXEC SPBUSCARCLIENTES 'UAD'

SELECT * FROM CLIENTES2 WHERE NOMBRE LIKE '%UAD%'

CREATE OR ALTER procedure SpSiguienteCodigoCliente
as
begin
	select max (CODCLI)+1 from CLIENTES2
end

EXEC SpSiguienteCodigoCliente

CREATE OR ALTER procedure SpInsertarCliente
@Nom varchar(30),
@Gen Varchar(10),
@Lat Float,
@Lon Float
as
begin
	insert into CLIENTES2 values (@Nom, @Gen, @Lat, @Lon)
end

EXEC SPInsertarCliente 'WILSON', 'MASCULINO',-63, -16
EXEC SPMOSTRARCLIENTES 


CREATE OR ALTER procedure SpModificaCliente
@Cod int,
@Nom varchar(30),
@Gen Varchar(10),
@Lat Float,
@Lon Float
as
begin
	update CLIENTES2 set Nombre = @Nom, Genero = @Gen, Latitud =  @Lat, LONGITUD =  @Lon 
	Where CODCLI = @Cod
end

CREATE OR ALTER procedure SpEliminaCliente
@Cod int
as
begin
	delete from CLIENTES2 Where CODCLI = @Cod
end
